### ISSUE TITLE
How do you make a driver?

### ISSUE THREAD

**Issue by wunadacatt** [TrueOpenVR/TrueOpenVR-Drivers#18]
I want to make a driver like keyboard.dll but have no clue how I tried researching by myself and realized I had no clue what I was doing. So if anyone out there knows please help

**Comment by r57zone** [comment]
Here is a simple driver (hmd + controllers) with keyboard buttons - https://github.com/r57zone/OpenVR-driver-for-DIY
Simple driver for hmd - https://github.com/r57zone/OpenVR-ArduinoHMD
Simple driver for controllers - https://github.com/r57zone/OpenVR-Additional-Arduino-Btns

**Comment by wunadacatt** [comment]
thank you
