### ISSUE TITLE
Mouse emulation

### ISSUE THREAD

**Issue by oivio** [TrueOpenVR/TrueOpenVR-Drivers#2]
This is just an Idea. Since Moonlight Game Streaming APK can emulate mouse movement with head rotations etc it can be useful to use is for VR?

**Comment by r57zone** [comment]
Yes, I agree, it is necessary. I will need to try to do it.

**Comment by r57zone** [comment]
Added utility for mouse emulation. You can download it in the [updated core pack](https://github.com/TrueOpenVR/TrueOpenVR-Core/releases/).
