### ISSUE TITLE
Нужны Комментарии, Много комментариев. 

### ISSUE THREAD

**Issue by Nakin72** [TrueOpenVR/TrueOpenVR-Drivers#5]
Не знаю как другим людям, но кажется что не хватает комментариев коде драйверов, особенно (для меня) в драйвере под Ардуино. Есть ли возможность их добавить? Не все функции понятны. Так же интересно как происходит "Общение" контроллера с вашей программой.

**Comment by r57zone** [comment]
Драйвер читает вывод на COM-порт, для HMD (RazorIMU) это 3 float значения, а для контроллеров (ArduinoControllers) 7 значений. 
Arduino просто выводит на COM-порт значения о вращении, тачпаде, состоянии триггера и кнопок.

**Comment by Nakin72** [comment]
А есть ли возможность сделать больше значений?

**Comment by Nakin72** [comment]
А Есть ли простой способ читать больше значений? (Координаты позиции, и/или вместо YPR Кватернионы использовать)

**Comment by Nakin72** [comment]
И еще, Ардуино данные шлет потоком? или сначала драйвер отсылает запрос и в ответ на него Контроллер шлет строку?

**Comment by r57zone** [comment]
Да, можно[ увеличить массив чтения](https://github.com/TrueOpenVR/TrueOpenVR-Drivers/blob/master/C%2B%2B/ArduinoControllers/ArduinoControllers.cpp#L45-L48) до нужного кол-ва.

Да, Arduino шлет потоком, никаких запросов на получение данных.

**Comment by Nakin72** [comment]
> Да, можно[ увеличить массив чтения](https://github.com/TrueOpenVR/TrueOpenVR-Drivers/blob/master/C%2B%2B/ArduinoControllers/ArduinoControllers.cpp#L45-L48) до нужного кол-ва.
Честно, вообще бы не додумался до этого, спасибо.
