### ISSUE TITLE
Could you support glove controllers?

### ISSUE THREAD

**Issue by bakwas247** [TrueOpenVR/TrueOpenVR-Drivers#6]
I have made glove controllers using flex sensors and buttons + joystick mounted on a glove. Would it be possible to add support for these with full finger tracking in vr? If not I am planning to try and learn C and the documentation to try and make my own driver but this will take months to a year for someone that is a complete beginner like me.

EDIT:
It is using an arduino.

**Comment by r57zone** [comment]
There is an [ArduinoControllers driver](https://github.com/TrueOpenVR/TrueOpenVR-Drivers/blob/master/C%2B%2B/ArduinoControllers/ArduinoControllers.cpp), you can fixed it to your needs with Microsoft Visual Studio 2017 or 2019.
Or you can make compatibility at the [Arduino firmware level](https://github.com/TrueOpenVR/TrueOpenVR-DIY/blob/master/Controllers/Arduino/Controller.ino).
