### ISSUE TITLE
PSMoveService centring bug?

### ISSUE THREAD

**Issue by r57zone** [TrueOpenVR/TrueOpenVR-Drivers#7]

**Comment by RamaRamesses** [comment]
Yup, it makes the controllers goes to some weird angles instead of pointing forward.

**Comment by r57zone** [comment]
Test ver 0.3
[PSMoveService64.zip](https://github.com/TrueOpenVR/TrueOpenVR-Drivers/files/4534959/PSMoveService64.zip)
I added centering on the PS button & start button of the first controller. Will this work correctly?

**Comment by RamaRamesses** [comment]
Yes, its finally centered my second controller forward. But only my second controller.
I press those buttons with my first controller but it resets my second controller instead the first controller.

**Comment by r57zone** [comment]
Test ver 0.4
[PSMoveService64.zip](https://github.com/TrueOpenVR/TrueOpenVR-Drivers/files/4534985/PSMoveService64.zip)
Press the PS button on both controllers

**Comment by RamaRamesses** [comment]
> Test ver 0.4
> [PSMoveService64.zip](https://github.com/TrueOpenVR/TrueOpenVR-Drivers/files/4534985/PSMoveService64.zip)
> Press the PS button on both controllers

It is now working correctly, thanks for your time!

**Comment by r57zone** [comment]
Cool, thanks for testing!

**Comment by r57zone** [comment]
Updated TrueOpenVR zip bundle (added x32 version and updated readme)

**Comment by RamaRamesses** [comment]
Anyway.. I think theres another problem
Yes, both controllers will head forwards when you press the centering button,
But, after some time the axes would become incorrect and I just realize my roll axis becomes yaw.
After I opened the psmoveconfigtool I notice the psmove controller is still drifted, while in steamvr it is correctly headed towards forward which makes the orientation confused and become uncorrect.
